#!/usr/bin/env bash
set -euf -o pipefail

# curl -s https://raw.githubusercontent.com/escribano/boot/master/apt | sudo bash

run() {
  printf %s "run: $*? " > /dev/tty
  read -n 1 answer < /dev/tty
  case $answer in
    [yY]*) eval "$@";;
  esac
}

if [[ $OSTYPE != linux* ]]; then 
	echo not running Linux
	exit 1
fi

# Check that we are superuser (i.e. $(id -u) is zero)
if (( $(id -u) ))
then
  echo "This script needs to run as root"
  exit 1
fi

apt update && sudo apt upgrade -y
run sudo apt install build-essential unzip
#run apt -qq list xfsprogs xfsdump nmap sysbench bonnie++ lsscsi rcconf
#curl git unzip -y
#sudo apt install xfsprogs xfsdump nmap -y
#sudo apt install sysbench bonnie++ -y
#sudo apt install lsscsi -y
#sudo apt install rcconf -y
#sudo apt install xfsdump nmap sysbench bonnie++ lsscsi rcconf
