#!/usr/bin/env bash
set -euf -o pipefail

# curl -s https://raw.githubusercontent.com/escribano/boot/master/home | sudo bash

run() {
  printf %s "run: $*? " > /dev/tty
  read -n 1 answer < /dev/tty
  case $answer in
    [yY]*) eval "$@";;
  esac
}

if [[ $OSTYPE != linux* ]]; then 
	echo not running Linux
	exit 1
fi

# Check that we are superuser (i.e. $(id -u) is zero)
if (( $(id -u) ))
then
  echo "This script needs to run as root"
  exit 1
fi

#apt update && sudo apt upgrade -y
#run sudo apt install build-essential unzip
#run apt -qq list xfsprogs xfsdump nmap sysbench bonnie++ lsscsi rcconf
#curl git unzip -y
#sudo apt install xfsprogs xfsdump nmap -y
#sudo apt install sysbench bonnie++ -y
#sudo apt install lsscsi -y
#sudo apt install rcconf -y

#sudo userdel -r ademir

sudo mkfs.ext4 /dev/xvdh
sudo mkdir -p /vol/home
echo "/dev/xvdh /vol/home ext4 defaults,noatime,nodiratime,nobarrier 0 0" | sudo tee -a /etc/fstab
sudo mount /vol/home


curl -s https://raw.githubusercontent.com/escribano/boot/master/user | sudo bash

sudo mv /home/ademir /vol/home/
sudo mkdir /home/ademir
echo "/vol/home/ademir /home/ademir none bind" | sudo tee -a /etc/fstab
sudo mount /home/ademir


sudo mkfs.ext4 /dev/xvdk
sudo mkdir -p /vol/core
echo "/dev/xvdk /vol/core ext4 defaults,noatime,nodiratime,nobarrier 0 0" | sudo tee -a /etc/fstab
sudo mount /vol/core
